language: go

go:
    - "1.11.1"
    - tip

install:
    - go get github.com/lugu/qiloop/...
    - go generate github.com/lugu/qiloop/bus/...
    - go generate github.com/lugu/qiloop/cmd/...
    - go generate github.com/lugu/qiloop/meta/...
    - go generate github.com/lugu/qiloop/type/...

script:
    - go test github.com/lugu/qiloop/... -race -coverprofile=coverage.txt -covermode=atomic -timeout 5m

after_success:
    - bash <(curl -s https://codecov.io/bash)
