language: go

go:
    - "1.10"
    - tip

install:
    - go get -d github.com/lugu/qiloop/...
    - go generate github.com/lugu/qiloop/object
    - go generate github.com/lugu/qiloop/meta/stage2

script: 
    - go get github.com/lugu/qiloop/cmd/info
    - go test github.com/lugu/qiloop/... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
