language: go

go:
    - "1.10"
    - tip

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

install:
    - go get github.com/lugu/qiloop/net
    - go get github.com/lugu/qiloop/meta/signature
    - go get github.com/lugu/qiloop/meta/stage1/...
    - go generate github.com/lugu/qiloop/meta/stage1
    - go get github.com/lugu/qiloop/meta/proxy
    - go get github.com/lugu/qiloop/meta/stage2/...
    - go generate github.com/lugu/qiloop/meta/stage2
    - go get github.com/lugu/qiloop/meta/stage3/...
    - go generate github.com/lugu/qiloop/meta/stage3

script: 
    - go get github.com/lugu/qiloop/cmd/info
    - go test -v github.com/lugu/qiloop/...

after_success:
    - go test -covermode=count -coverprofile=profile.cov
    - goveralls -coverprofile=profile.cov -service=travis-ci
