language: go

go:
    - "1.11.1"
    - tip

install:
    - go get -d -t github.com/lugu/qiloop/...
    - go generate github.com/lugu/qiloop/type/object
    - go generate github.com/lugu/qiloop/meta/stage2
    - go generate github.com/lugu/qiloop/bus/services

script:
    - go test github.com/lugu/qiloop/... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
