language: go

go:
    - "1.10"
    - tip

install:
    - go get github.com/lugu/qiloop/session
    - go get github.com/lugu/qiloop/meta/signature
    - go get github.com/lugu/qiloop/meta/stage1/...
    - go generate github.com/lugu/qiloop/meta/stage1
    - go get github.com/lugu/qiloop/meta/proxy
    - go get github.com/lugu/qiloop/meta/stage2/...
    - go generate github.com/lugu/qiloop/meta/stage2
    - go get github.com/lugu/qiloop/meta/stage3/...
    - go generate github.com/lugu/qiloop/meta/stage3

script: 
    - go get github.com/lugu/qiloop/cmd/info
    - go test github.com/lugu/qiloop/... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
