package unknown
interface ALMemory
	fn registerEvent(P0: uint32, P1: uint32, P2: uint64) -> uint64 //uid:0
	fn unregisterEvent(P0: uint32, P1: uint32, P2: uint64) //uid:1
	fn metaObject(P0: uint32) -> MetaObject //uid:2
	fn terminate(P0: uint32) //uid:3
	fn property(P0: any) -> any //uid:5
	fn setProperty(P0: any, P1: any) //uid:6
	fn properties() -> Vec<str> //uid:7
	fn registerEventWithSignature(P0: uint32, P1: uint32, P2: uint64, P3: str) -> uint64 //uid:8
	fn isStatsEnabled() -> bool //uid:80
	fn enableStats(P0: bool) //uid:81
	fn stats() -> Map<uint32,MethodStatistics> //uid:82
	fn clearStats() //uid:83
	fn isTraceEnabled() -> bool //uid:84
	fn enableTrace(P0: bool) //uid:85
	fn exit() //uid:100
	fn __pCall(P0: uint32, P1: Vec<any>) -> int32 //uid:101
	fn pCall(P0: any) -> any //uid:102
	fn version() -> str //uid:103
	fn ping() -> bool //uid:104
	fn getMethodList() -> Vec<str> //uid:105
	fn getMethodHelp(methodName: str) -> any //uid:106
	fn getModuleHelp() -> any //uid:107
	fn wait(id: int32,timeoutPeriod: int32) -> bool //uid:108
	fn isRunning(id: int32) -> bool //uid:109
	fn stop(id: int32) //uid:110
	fn getBrokerName() -> str //uid:111
	fn getUsage(name: str) -> str //uid:112
	fn declareEvent(eventName: str) //uid:113
	fn declareEvent(eventName: str,extractorName: str) //uid:114
	fn getData(key: str) -> any //uid:115
	fn getData(key: str,deprecatedParameter: int32) -> any //uid:116
	fn subscriber(eventName: str) -> obj //uid:117
	fn getTimestamp(key: str) -> any //uid:118
	fn getEventHistory(key: str) -> any //uid:119
	fn getDataList(filter: str) -> Vec<str> //uid:120
	fn getDataListName() -> Vec<str> //uid:121
	fn getDataOnChange(key: str,deprecatedParameter: int32) -> any //uid:122
	fn getDataPtr(key: str) -> unknown //uid:123
	fn getEventList() -> Vec<str> //uid:124
	fn getExtractorEvent(extractorName: str) -> Vec<str> //uid:125
	fn getListData(keyList: any) -> any //uid:126
	fn getMicroEventList() -> Vec<str> //uid:127
	fn getSubscribers(name: str) -> Vec<str> //uid:128
	fn getType(key: str) -> str //uid:129
	fn insertData(key: str,value: int32) //uid:130
	fn insertData(key: str,value: float32) //uid:131
	fn insertData(key: str,value: str) //uid:132
	fn insertData(key: str,data: any) //uid:133
	fn insertListData(list: any) //uid:134
	fn raiseEvent(name: str,value: any) //uid:135
	fn raiseMicroEvent(name: str,value: any) //uid:136
	fn removeData(key: str) //uid:137
	fn removeEvent(name: str) //uid:138
	fn removeMicroEvent(name: str) //uid:139
	fn subscribeToEvent(name: str,callbackModule: str,callbackMethod: str) //uid:140
	fn subscribeToEvent(name: str,callbackModule: str,callbackMessage: str,callbacMethod: str) //uid:141
	fn subscribeToMicroEvent(name: str,callbackModule: str,callbackMessage: str,callbackMethod: str) //uid:142
	fn unregisterModuleReference(moduleName: str) //uid:143
	fn _perf() //uid:144
	fn unsubscribeToEvent(name: str,callbackModule: str) //uid:145
	fn unsubscribeToMicroEvent(name: str,callbackModule: str) //uid:146
	fn _insertObject(name: str,buffer: any,bufferSize: int32) //uid:147
	fn _subscribeOnDataSetTimePolicy(name: str,callbackModule: str,nTimePolicy: int32) //uid:148
	fn _subscribeOnDataSetSynchronizeResponse(name: str,callbackModule: str,synchronizedResponse: bool) //uid:149
	fn setDescription(name: str,description: str) //uid:150
	fn getDescriptionList(keylist: Vec<str>) -> any //uid:151
	fn addMapping(service: str,signal: str,event: str) //uid:152
	fn addMapping(service: str,signalEvent: Map<str,str>) //uid:153
	sig traceObject(P0: EventTrace) //uid:86
end
struct MetaMethodParameter
	name: str
	description: str
end
struct MetaMethod
	uid: uint32
	returnSignature: str
	name: str
	parametersSignature: str
	description: str
	parameters: Vec<MetaMethodParameter>
	returnDescription: str
end
struct MetaSignal
	uid: uint32
	name: str
	signature: str
end
struct MetaProperty
	uid: uint32
	name: str
	signature: str
end
struct MetaObject
	methods: Map<uint32,MetaMethod>
	signals: Map<uint32,MetaSignal>
	properties: Map<uint32,MetaProperty>
	description: str
end
struct MinMaxSum
	minValue: float32
	maxValue: float32
	cumulatedValue: float32
end
struct MethodStatistics
	count: uint32
	wall: MinMaxSum
	user: MinMaxSum
	system: MinMaxSum
end
struct timeval
	tv_sec: int64
	tv_usec: int64
end
struct EventTrace
	id: uint32
	kind: int32
	slotId: uint32
	arguments: any
	timestamp: timeval
	userUsTime: int64
	systemUsTime: int64
	callerContext: uint32
	calleeContext: uint32
end
