# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    environment:
       CC_TEST_REPORTER_ID: 0785bba858e3306249391d2bfed7d0893eee93420195ad1398d5e9231c0ff680
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: pwd
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: go version
      - run: go generate ./bus/...
      - run: go generate ./meta/...
      - run: go generate ./type/...
      - run: go generate ./examples/...
      - run: go build ./...
      - run: go vet -composites=false ./...
      - run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic -timeout 2m
      - run: bash <(curl -s https://codecov.io/bash)
      - run: sed 's#github.com/lugu/qiloop/##g' coverage.txt > c.out
      - run: ./cc-test-reporter after-build
