# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    environment:
       CC_TEST_REPORTER_ID: 0785bba858e3306249391d2bfed7d0893eee93420195ad1398d5e9231c0ff680
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/lugu/qiloop
    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: go version
      - run: go get github.com/lugu/qiloop/...
      - run: go generate github.com/lugu/qiloop/bus/...
      - run: go generate github.com/lugu/qiloop/cmd/...
      - run: go generate github.com/lugu/qiloop/meta/...
      - run: go generate github.com/lugu/qiloop/type/...
      - run: go test github.com/lugu/qiloop/... -race -coverprofile=coverage.txt -covermode=atomic -timeout 2m
      - run: bash <(curl -s https://codecov.io/bash)
      - run: mv coverage.txt c.out
      - run: ./cc-test-reporter after-build
