package tester

interface Dummy
        fn hello() -> Bomb
        fn attack(b: Bomb)
        sig ping(msg: str)
        prop status(msg: Map<str,int32>)
        prop coordinate(x: int32, y: int32)
end

interface Bomb
        sig boom(energy: int32)
end
